spring:
  application:
    name: session
  datasource:
    url: jdbc:mysql://localhost:3306/session?useSSL=false&serverTimezone=Asia/Tokyo
    username: user
    password: azp!pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true